"""add unique key constraint

Revision ID: 05b7b3dac1cb
Revises: 45aff862251d
Create Date: 2025-05-09 01:46:54.457833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b7b3dac1cb'
down_revision: Union[str, None] = '45aff862251d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bangkok_budget_mis_id'), 'bangkok_budget', ['mis_id'], unique=True)
    op.create_unique_constraint('uq_bangkok_budget_mis_id', 'bangkok_budget', ['mis_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bangkok_budget_mis_id', 'bangkok_budget', type_='unique')
    op.drop_index(op.f('ix_bangkok_budget_mis_id'), table_name='bangkok_budget')
    # ### end Alembic commands ###
