"""update riskpoint objectid to traffy fondue

Revision ID: 675f8ed2fd22
Revises: ee3f449cd195
Create Date: 2025-05-01 15:17:21.916612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675f8ed2fd22'
down_revision: Union[str, None] = 'ee3f449cd195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffy_fondue_citizen_complaint', sa.Column('riskpoint_objectid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffy_fondue_citizen_complaint', 'riskpoint_objectid')
    # ### end Alembic commands ###
