"""add canal and sewarage dredging tables

Revision ID: c14f566e43d3
Revises: 6c242567bbbc
Create Date: 2025-04-28 23:54:51.663834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14f566e43d3'
down_revision: Union[str, None] = '6c242567bbbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canal_dredging_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_number', sa.Integer(), nullable=True),
    sa.Column('district_agency', sa.String(length=255), nullable=True),
    sa.Column('total_canals_assigned', sa.Integer(), nullable=True),
    sa.Column('total_length_assigned_m', sa.Integer(), nullable=True),
    sa.Column('regularly_maintained_canals', sa.Integer(), nullable=True),
    sa.Column('regularly_maintained_length_m', sa.Integer(), nullable=True),
    sa.Column('periodically_flowed_canals', sa.Integer(), nullable=True),
    sa.Column('periodically_flowed_length_m', sa.Integer(), nullable=True),
    sa.Column('total_maintained_flowed_length_m', sa.Integer(), nullable=True),
    sa.Column('percent_maintained_flowed', sa.Float(), nullable=True),
    sa.Column('planned_dredging_canals', sa.Integer(), nullable=True),
    sa.Column('planned_dredging_length_m', sa.Integer(), nullable=True),
    sa.Column('annual_budgeted_canals', sa.Integer(), nullable=True),
    sa.Column('annual_budgeted_length_m', sa.Integer(), nullable=True),
    sa.Column('annual_budget', sa.Integer(), nullable=True),
    sa.Column('annual_committed_budget', sa.String(length=255), nullable=True),
    sa.Column('dredged_length_annual_budget_m', sa.Integer(), nullable=True),
    sa.Column('percent_dredged_annual_budget', sa.Float(), nullable=True),
    sa.Column('additional_budgeted_canals', sa.Integer(), nullable=True),
    sa.Column('additional_budgeted_length_m', sa.Integer(), nullable=True),
    sa.Column('supplementary_budget', sa.Integer(), nullable=True),
    sa.Column('supplementary_committed_budget', sa.Integer(), nullable=True),
    sa.Column('dredged_length_supplementary_budget_m', sa.Integer(), nullable=True),
    sa.Column('percent_dredged_supplementary_budget', sa.Float(), nullable=True),
    sa.Column('total_dredged_canals', sa.Integer(), nullable=True),
    sa.Column('total_percent_dredged', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('district_code', sa.String(length=50), nullable=True),
    sa.Column('buddhist_year', sa.Integer(), nullable=True),
    sa.Column('day_period', sa.String(length=50), nullable=True),
    sa.Column('month', sa.String(length=50), nullable=True),
    sa.Column('record_date', sa.String(length=50), nullable=True),
    sa.Column('reporting_date', sa.String(length=50), nullable=True),
    sa.Column('plan_sequence', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sewerage_dredging_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_number', sa.Integer(), nullable=True),
    sa.Column('district_agency', sa.String(length=255), nullable=True),
    sa.Column('total_alleys', sa.Integer(), nullable=True),
    sa.Column('total_length_m', sa.Integer(), nullable=True),
    sa.Column('alleys_not_cleaned_this_year', sa.Integer(), nullable=True),
    sa.Column('length_not_cleaned_this_year_m', sa.Integer(), nullable=True),
    sa.Column('alleys_cleaned_this_year', sa.Integer(), nullable=True),
    sa.Column('length_cleaned_this_year_m', sa.Integer(), nullable=True),
    sa.Column('planned_alleys_by_district_labor', sa.Integer(), nullable=True),
    sa.Column('planned_length_by_district_labor_m', sa.Integer(), nullable=True),
    sa.Column('executed_alleys_by_district_labor', sa.Integer(), nullable=True),
    sa.Column('executed_length_by_district_labor_m', sa.Integer(), nullable=True),
    sa.Column('percent_executed_by_district_labor', sa.Float(), nullable=True),
    sa.Column('planned_alleys_by_dop', sa.Integer(), nullable=True),
    sa.Column('planned_length_by_dop_m', sa.Integer(), nullable=True),
    sa.Column('annual_budgeted_alleys_by_dop', sa.Integer(), nullable=True),
    sa.Column('annual_budgeted_length_by_dop_m', sa.Integer(), nullable=True),
    sa.Column('executed_length_annual_by_dop_m', sa.Integer(), nullable=True),
    sa.Column('percent_executed_annual_by_dop', sa.Float(), nullable=True),
    sa.Column('supplementary_budgeted_alleys_by_dop', sa.Integer(), nullable=True),
    sa.Column('supplementary_budgeted_length_by_dop_m', sa.Integer(), nullable=True),
    sa.Column('executed_length_supplementary_by_dop_m', sa.Integer(), nullable=True),
    sa.Column('percent_executed_supplementary_by_dop', sa.Float(), nullable=True),
    sa.Column('planned_alleys_by_private', sa.Integer(), nullable=True),
    sa.Column('planned_length_by_private_m', sa.Integer(), nullable=True),
    sa.Column('annual_budgeted_alleys_by_private', sa.Integer(), nullable=True),
    sa.Column('annual_budgeted_length_by_private_m', sa.Integer(), nullable=True),
    sa.Column('executed_length_annual_by_private_m', sa.Integer(), nullable=True),
    sa.Column('percent_executed_annual_by_private', sa.Float(), nullable=True),
    sa.Column('supplementary_budgeted_alleys_by_private', sa.Integer(), nullable=True),
    sa.Column('supplementary_budgeted_length_by_private_m', sa.Integer(), nullable=True),
    sa.Column('executed_length_supplementary_by_private_m', sa.Integer(), nullable=True),
    sa.Column('percent_executed_supplementary_by_private', sa.Float(), nullable=True),
    sa.Column('manhole_cover_repaired', sa.Integer(), nullable=True),
    sa.Column('grating_repaired', sa.Integer(), nullable=True),
    sa.Column('curb_repaired', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('district_code', sa.String(length=50), nullable=True),
    sa.Column('buddhist_year', sa.Integer(), nullable=True),
    sa.Column('day_period', sa.String(length=50), nullable=True),
    sa.Column('month', sa.String(length=50), nullable=True),
    sa.Column('record_date', sa.String(length=50), nullable=True),
    sa.Column('reporting_date', sa.String(length=50), nullable=True),
    sa.Column('plan_sequence', sa.String(length=50), nullable=True),
    sa.Column('annual_budget_by_private_baht', sa.Float(), nullable=True),
    sa.Column('supplementary_budget_by_private_baht', sa.Float(), nullable=True),
    sa.Column('executed_alleys_annual_by_private', sa.Integer(), nullable=True),
    sa.Column('executed_alleys_supplementary_by_private', sa.Integer(), nullable=True),
    sa.Column('annual_budget_by_dop_baht', sa.Float(), nullable=True),
    sa.Column('supplementary_budget_by_dop_baht', sa.Float(), nullable=True),
    sa.Column('executed_alleys_annual_by_dop', sa.Integer(), nullable=True),
    sa.Column('executed_alleys_supplementary_by_dop', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sewerage_dredging_progress')
    op.drop_table('canal_dredging_progress')
    # ### end Alembic commands ###
