"""create test table

Revision ID: ebe14453ce76
Revises: 8426a495ecd4
Create Date: 2025-05-08 12:01:14.999797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe14453ce76'
down_revision: Union[str, None] = '8426a495ecd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rainfall_and_flood_summary_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=True),
    sa.Column('risk_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('flood_sensor_code', sa.String(length=255), nullable=True),
    sa.Column('flood_code', sa.String(length=255), nullable=True),
    sa.Column('hour', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_flood', sa.Float(), nullable=True),
    sa.Column('flood_duration_minutes', sa.Float(), nullable=True),
    sa.Column('rainfall_sensor_code', sa.String(length=255), nullable=True),
    sa.Column('rf1hr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rainfall_and_flood_summary_2')
    # ### end Alembic commands ###
