"""update all numerical to string type

Revision ID: f8dbc7d8c3ed
Revises: 0d1144717de0
Create Date: 2025-05-10 14:22:04.452826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8dbc7d8c3ed'
down_revision: Union[str, None] = '0d1144717de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bangkok_budget_mis_id'), 'bangkok_budget', ['mis_id'], unique=True)
    op.alter_column('canal_dredging_progress', 'total_canals_assigned',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'total_length_assigned_m',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'regularly_maintained_canals',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'regularly_maintained_length_m',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'periodically_flowed_canals',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'periodically_flowed_length_m',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'total_maintained_flowed_length_m',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'planned_dredging_canals',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'planned_dredging_length_m',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'annual_budgeted_canals',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'annual_budgeted_length_m',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'annual_budget',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'dredged_length_annual_budget_m',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'additional_budgeted_canals',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'additional_budgeted_length_m',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'supplementary_budget',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'supplementary_committed_budget',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'dredged_length_supplementary_budget_m',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'total_dredged_canals',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'buddhist_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('rainfall_sensor', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rainfall_sensor', 'created_at')
    op.alter_column('canal_dredging_progress', 'buddhist_year',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'total_dredged_canals',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'dredged_length_supplementary_budget_m',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'supplementary_committed_budget',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'supplementary_budget',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'additional_budgeted_length_m',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'additional_budgeted_canals',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'dredged_length_annual_budget_m',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'annual_budget',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'annual_budgeted_length_m',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'annual_budgeted_canals',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'planned_dredging_length_m',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'planned_dredging_canals',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'total_maintained_flowed_length_m',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'periodically_flowed_length_m',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'periodically_flowed_canals',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'regularly_maintained_length_m',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'regularly_maintained_canals',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'total_length_assigned_m',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('canal_dredging_progress', 'total_canals_assigned',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_bangkok_budget_mis_id'), table_name='bangkok_budget')
    # ### end Alembic commands ###
