version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    restart: always

  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    entrypoint: ["/bin/bash", "-c", "airflow db migrate && airflow users create --username \"${AIRFLOW_ADMIN_USERNAME:-admin}\" --firstname \"${AIRFLOW_ADMIN_FIRSTNAME:-Admin}\" --lastname \"${AIRFLOW_ADMIN_LASTNAME:-User}\" --role Admin --email \"${AIRFLOW_ADMIN_EMAIL:-admin@example.com}\" --password \"${AIRFLOW_ADMIN_PASSWORD:-admin}\" && airflow webserver"]
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - BMA_DB_USER=${BMA_DB_USER}
      - BMA_DB_PASSWORD=${BMA_DB_PASSWORD}
      - BMA_DB_HOST=${BMA_DB_HOST}
      - BMA_DB_PORT=${BMA_DB_PORT}
      - BMA_DB_NAME=${BMA_DB_NAME}
      - BMA_API_USERNAME=${BMA_API_USERNAME}
      - BMA_API_PASSWORD=${BMA_API_PASSWORD}
      - AIRFLOW_ADMIN_USERNAME=${AIRFLOW_ADMIN_USERNAME}
      - AIRFLOW_ADMIN_FIRSTNAME=${AIRFLOW_ADMIN_FIRSTNAME}
      - AIRFLOW_ADMIN_LASTNAME=${AIRFLOW_ADMIN_LASTNAME}
      - AIRFLOW_ADMIN_EMAIL=${AIRFLOW_ADMIN_EMAIL}
      - AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./include:/opt/airflow/include
      - ./config:/opt/airflow/config
      - ./config/airflow.cfg:/opt/airflow/airflow.cfg
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  scheduler:
    build: .
    restart: always
    depends_on:
      - webserver
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - BMA_DB_USER=${BMA_DB_USER}
      - BMA_DB_PASSWORD=${BMA_DB_PASSWORD}
      - BMA_DB_HOST=${BMA_DB_HOST}
      - BMA_DB_PORT=${BMA_DB_PORT}
      - BMA_DB_NAME=${BMA_DB_NAME}
      - BMA_API_USERNAME=${BMA_API_USERNAME}
      - BMA_API_PASSWORD=${BMA_API_PASSWORD}
      - AIRFLOW_ADMIN_USERNAME=${AIRFLOW_ADMIN_USERNAME}
      - AIRFLOW_ADMIN_FIRSTNAME=${AIRFLOW_ADMIN_FIRSTNAME}
      - AIRFLOW_ADMIN_LASTNAME=${AIRFLOW_ADMIN_LASTNAME}
      - AIRFLOW_ADMIN_EMAIL=${AIRFLOW_ADMIN_EMAIL}
      - AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./include:/opt/airflow/include
      - ./config:/opt/airflow/config
      - ./config/airflow.cfg:/opt/airflow/airflow.cfg
    command: scheduler

volumes:
  postgres-db-volume:
